baseURL = "http://mciantyre.github.io/"
languageCode = "en-us"
title = "mciantyre"

[params]
mode = "dark"
subtitle = "Technical blog and ramblings"

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1

[taxonomies]
tag = "tags"