baseURL = "http://mciantyre.github.io/"
languageCode = "en-us"
title = "mciantyre"
theme = "ezhil"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = "dark"
subtitle = "Technical blog and ramblings"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mciantyre"

[taxonomies]
tag = "tags"